<?php
if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();
$styledata = Array('id' => 19, 'style_name' => 'style19', 'css' => 'heading-font-size |20| heading-font-color |#99069e| heading-font-active-color |#8308d4| heading-font-familly |Open+Sans| heading-font-weight |600| heading-text-align |center| heading-width |190| heading-margin-bottom |10| heading-padding |20| content-font-size |16| content-font-color |#787878| content-background-color |#ffffff| content-padding-top |30| content-padding-right |30| content-padding-bottom |30| content-padding-left |30|content-line-height |1.5| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |center| content-border-radius |5|content-box-shadow-Blur |10| content-box-shadow-color |rgba(219, 219, 219, 1)| heading-font-style |normal| content-box-shadow-Horizontal |0| content-box-shadow-Vertical |0| content-box-shadow-Spread |0| custom-css ||||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 19, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis orci risus. Aliquam pellentesque suscipit nisi, in varius nisl suscipit id. Aenean convallis tellus id metus rutrum, vitae mollis libero vehicula. Nullam nec nisi a ipsum vehicula dictum sed id nunc. Aenean aliquet malesuada elementum. Curabitur bibendum elit at sapien convallis maximus. Ut sit amet urna diam. Fusce eu volutpat ipsum. Nullam neque risus, rhoncus in tincidunt sed, suscipit nec sapien. Donec et gravida dui, vitae vulputate dui. Suspendisse finibus, risus tempus scelerisque mattis, massa purus euismod urna, vitae euismod diam nisi ut nisl. Fusce consectetur dui a feugiat iaculis. Morbi vitae felis in quam sagittis euismod.</p> <p>&nbsp;</p> <p>Integer euismod ante in sem iaculis convallis. Nulla eu ex quis enim accumsan fermentum id id sem. Morbi molestie elit mi, sit amet dapibus elit sodales at. Duis blandit lorem ut lacus placerat, laoreet aliquam nibh lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vitae consectetur libero. Maecenas iaculis molestie efficitur. Donec rhoncus, nibh vitae aliquet sagittis, orci justo vehicula leo, quis rhoncus dolor ante malesuada mi. Vivamus aliquam, tellus sit amet venenatis convallis, ligula diam venenatis quam, ac mattis neque diam quis metus. Nunc et pellentesque nibh. Fusce in ligula venenatis, fringilla justo quis, laoreet dolor.</p>', 'css' => 'fas fa-address-book'),
    1 => Array('id' => 2, 'styleid' => 19, 'title' => 'Default Title', 'files' => '<p>Integer euismod ante in sem iaculis convallis. Nulla eu ex quis enim accumsan fermentum id id sem. Morbi molestie elit mi, sit amet dapibus elit sodales at. Duis blandit lorem ut lacus placerat, laoreet aliquam nibh lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vitae consectetur libero. Maecenas iaculis molestie efficitur. Donec rhoncus, nibh vitae aliquet sagittis, orci justo vehicula leo, quis rhoncus dolor ante malesuada mi. Vivamus aliquam, tellus sit amet venenatis convallis, ligula diam venenatis quam, ac mattis neque diam quis metus. Nunc et pellentesque nibh. Fusce in ligula venenatis, fringilla justo quis, laoreet dolor.</p> <p>&nbsp;</p> <p>Nullam ut ante neque. Nam nec sem a metus pharetra lobortis quis sed lorem. Morbi congue sapien non dolor interdum, quis pretium quam placerat. Fusce dictum lacinia massa sed fermentum. Nam vel euismod leo. Mauris quis felis quis velit faucibus ornare sed vel dolor. Sed ut augue ut libero consectetur sagittis. Vestibulum ullamcorper sagittis magna eget consectetur. Integer ac orci non ipsum mattis varius sed a sem. Donec in erat sed arcu tincidunt lobortis. Sed ut vulputate nisl.</p>', 'css' => 'fab fa-algolia'),
    2 => Array('id' => 3, 'styleid' => 19, 'title' => 'Default Title', 'files' => '<p>Nullam ut ante neque. Nam nec sem a metus pharetra lobortis quis sed lorem. Morbi congue sapien non dolor interdum, quis pretium quam placerat. Fusce dictum lacinia massa sed fermentum. Nam vel euismod leo. Mauris quis felis quis velit faucibus ornare sed vel dolor. Sed ut augue ut libero consectetur sagittis. Vestibulum ullamcorper sagittis magna eget consectetur. Integer ac orci non ipsum mattis varius sed a sem. Donec in erat sed arcu tincidunt lobortis. Sed ut vulputate nisl.</p>  <p>&nbsp;</p> <p>Nullam et massa at mauris molestie placerat eget et dui. Suspendisse euismod nisl sit amet arcu convallis, a iaculis mi vulputate. Quisque quis lacinia tortor. Praesent ultrices mauris ac purus sagittis, vel volutpat mauris lacinia. Donec diam arcu, porta at nisl a, pretium dictum arcu. Nulla vestibulum ultricies tellus, vitae commodo arcu vulputate quis. Curabitur eget justo nec elit ullamcorper tempor. Nam et lacus molestie, placerat mauris elementum, laoreet sapien.</p>', 'css' => 'fab fa-adn'),
    3 => Array('id' => 4, 'styleid' => 19, 'title' => 'Default Title', 'files' => '<p>Nullam et massa at mauris molestie placerat eget et dui. Suspendisse euismod nisl sit amet arcu convallis, a iaculis mi vulputate. Quisque quis lacinia tortor. Praesent ultrices mauris ac purus sagittis, vel volutpat mauris lacinia. Donec diam arcu, porta at nisl a, pretium dictum arcu. Nulla vestibulum ultricies tellus, vitae commodo arcu vulputate quis. Curabitur eget justo nec elit ullamcorper tempor. Nam et lacus molestie, placerat mauris elementum, laoreet sapien.</p> <p>&nbsp;</p> <p>Aenean magna justo, ultrices eget ornare ac, condimentum vel nisi. In pharetra lorem neque, non ornare eros finibus quis. Donec semper erat nisl, at congue risus pharetra vel. Vivamus faucibus dignissim velit, aliquet porta diam suscipit et. Ut quis convallis elit. Nunc vehicula ac orci id sollicitudin. Etiam porta gravida neque, ut dignissim lacus consectetur id. Nulla cursus sit amet enim quis vulputate. Donec quam arcu, pretium vel nisi et, condimentum sagittis ipsum. Donec eleifend, odio vitae egestas rutrum, turpis lacus ultrices neque, eu rhoncus odio nisl id urna. Nunc dapibus mi sed lectus facilisis luctus. Morbi porta orci sed risus consequat pulvinar. Cras in lorem mauris.</p>', 'css' => 'fas fa-ambulance')
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);
