<?php

if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();

$styledata = Array('id' => 20, 'style_name' => 'style20', 'css' => 'heading-font-size |20| heading-font-familly |Open+Sans| heading-font-weight |600| heading-text-align |flex-start| heading-width |200| heading-padding |20| heading-margin-right |5| heading-border-radius |5| content-font-size |16| content-padding-top |30|content-padding-right |30| content-padding-bottom |30| content-padding-left |30|content-line-height |1.5| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |left| heading-font-style |normal| custom-css |||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 1, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tincidunt orci non nisl vulputate, in aliquet augue pellentesque. Phasellus nec sodales enim, in interdum nisi. Integer et purus in massa hendrerit maximus vestibulum at erat. Praesent tempus interdum tortor. Pellentesque faucibus dui erat, eget congue odio consequat at.</p> <p>&nbsp;</p><p>Curabitur varius hendrerit augue, eget egestas odio tempor quis. Duis id molestie dolor. Vestibulum pharetra, quam sit amet placerat accumsan, magna orci consectetur ex, porta suscipit enim erat sit amet orci. Duis ornare tortor orci, a finibus mi tincidunt cursus. Quisque porta lorem vel placerat aliquet. &nbsp; Etiam a ornare mi, ut fringilla lorem. Praesent interdum vestibulum semper. Vivamus feugiat odio nibh, eget ultrices mauris euismod et. Morbi eleifend felis et mauris tempus auctor. Proin et auctor orci, vel facilisis metus. Suspendisse enim orci, dictum vel eros eu, dictum congue sem. Nullam vitae venenatis arcu, a porttitor eros. Vivamus tincidunt pulvinar ullamcorper. Aenean blandit libero scelerisque augue porta commodo.</p>', 'css' => 'color |#ffffff| background |rgba(136, 0, 209, 1)|'),
    1 => Array('id' => 2, 'styleid' => 1, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tincidunt orci non nisl vulputate, in aliquet augue pellentesque. Phasellus nec sodales enim, in interdum nisi. Integer et purus in massa hendrerit maximus vestibulum at erat. Praesent tempus interdum tortor. Pellentesque faucibus dui erat, eget congue odio consequat at.</p><p>&nbsp;</p><p>Curabitur varius hendrerit augue, eget egestas odio tempor quis. Duis id molestie dolor. Vestibulum pharetra, quam sit amet placerat accumsan, magna orci consectetur ex, porta suscipit enim erat sit amet orci. Duis ornare tortor orci, a finibus mi tincidunt cursus. Quisque porta lorem vel placerat aliquet. &nbsp; Etiam a ornare mi, ut fringilla lorem. Praesent interdum vestibulum semper. Vivamus feugiat odio nibh, eget ultrices mauris euismod et. Morbi eleifend felis et mauris tempus auctor. Proin et auctor orci, vel facilisis metus. Suspendisse enim orci, dictum vel eros eu, dictum congue sem. Nullam vitae venenatis arcu, a porttitor eros. Vivamus tincidunt pulvinar ullamcorper. Aenean blandit libero scelerisque augue porta commodo.</p>', 'css' => 'color |#ffffff| background |rgba(232, 0, 232, 1)|'),
    2 => Array('id' => 3, 'styleid' => 1, 'title' => 'Default Title', 'files' => '<p>Sed blandit vestibulum lectus. Curabitur eget mi scelerisque enim scelerisque dictum. Duis fermentum odio id nibh faucibus rhoncus. Nunc quis purus in mauris mattis fringilla. Fusce feugiat placerat sollicitudin. In facilisis accumsan laoreet. Aenean nisi tortor, varius ac elit et, viverra fermentum sem. Praesent posuere, dui at feugiat porttitor, orci urna mattis enim, nec bibendum dui sapien id ligula. &nbsp; Suspendisse sit amet ex non urna fringilla malesuada. Aenean posuere sapien quis elementum tincidunt. Donec rutrum ornare vulputate. Nam magna orci, auctor vitae egestas at, tristique non elit. Etiam nec magna feugiat, efficitur leo vel, dictum neque.</p> <p>&nbsp;</p><p>Nullam faucibus ante et sem accumsan porttitor. Curabitur non lobortis turpis, quis consectetur sapien. Mauris vel lorem ut risus pulvinar luctus ut sit amet leo. Sed consectetur lorem magna, non aliquam risus vehicula sit amet. Nulla facilisi. Pellentesque vulputate tellus vel quam elementum convallis. Duis eu massa ante.</p>', 'css' => 'color |#ffffff| background |rgba(138, 133, 0, 1)|'),
    3 => Array('id' => 4, 'styleid' => 1, 'title' => 'Default Title', 'files' => '<p>Suspendisse sit amet ex non urna fringilla malesuada. Aenean posuere sapien quis elementum tincidunt. Donec rutrum ornare vulputate. Nam magna orci, auctor vitae egestas at, tristique non elit. Etiam nec magna feugiat, efficitur leo vel, dictum neque. Nullam faucibus ante et sem accumsan porttitor. Curabitur non lobortis turpis, quis consectetur sapien. Mauris vel lorem ut risus pulvinar luctus ut sit amet leo. Sed consectetur lorem magna, non aliquam risus vehicula sit amet. Nulla facilisi. Pellentesque vulputate tellus vel quam elementum convallis.</p> <p>&nbsp;</p><p>Duis eu massa ante. &nbsp; Quisque in imperdiet nulla, eget finibus velit. Ut congue sapien enim, ut dignissim leo tempor congue. Praesent ac felis eget enim dictum accumsan eu sed lacus. Etiam in nisl dictum, commodo odio vel, eleifend sem. Quisque eget finibus dui. Proin eget nibh accumsan, lobortis ligula at, finibus sem. Duis nec nulla laoreet, tempor velit sit amet, lacinia nisi. Quisque viverra quam blandit nibh semper, at imperdiet enim sagittis. Aliquam ac turpis non urna fermentum sagittis at eget ante. Pellentesque tristique bibendum mattis.</p>', 'css' => 'color |#ffffff| background |rgba(0, 148, 20, 1)|')
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);
