<?php 
if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();

$styledata = Array('id' => 3, 'style_name' => 'style3', 'css' => 'heading-font-size |20| heading-font-color |#ffffff| heading-background-color |rgba(0, 186, 164, 1)| heading-border-color |#04cee0| heading-font-active-color |#ffffff| heading-background-active-color |rgba(0, 189, 54, 1)| heading-border-active-color |#cf04ad| heading-font-familly |Open+Sans| heading-font-weight |500| heading-text-align |flex-start| heading-width |160| heading-padding |15|heading-box-shadow-Blur |13| heading-box-shadow-color |rgba(217, 217, 217, 1)| content-font-size |16| content-font-color |#919191| content-background-color |rgba(255, 255, 255, 1)| content-padding-top |30| content-padding-right |20| content-padding-bottom |30| content-padding-left |20| content-line-height |1.4| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |left| content-box-shadow-color |#d4d4d4| content-box-shadow-Blur |20| heading-margin-right |10| heading-box-shadow-Horizontal |0| heading-box-shadow-Vertical |0| heading-box-shadow-Spread |0| content-box-shadow-Horizontal |0| content-box-shadow-Vertical |0| content-box-shadow-Spread |0| heading-font-style |normal| custom-css |||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 3, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>  <p>&nbsp;</p> <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste</p>', 'css' => 'fas fa-address-book'),
    1 => Array('id' => 2, 'styleid' => 3, 'title' => 'Default Title', 'files' => '<p>Aenean tempor dui ut tortor semper consequat. Donec sit amet ligula tempor ante vestibulum varius. Sed sodales sollicitudin vestibulum. Duis malesuada tortor vitae nunc porta facilisis. Donec efficitur purus quis vulputate vehicula. Curabitur egestas rutrum orci quis consequat. Sed tincidunt tempor feugiat.</p> <p>&nbsp;</p> <p>Mauris tempor nibh erat, eget lacinia justo porta ut. Nullam a elit vitae nunc semper tincidunt. Aliquam erat volutpat. Phasellus sollicitudin dapibus nibh et varius. Sed sapien turpis, euismod et erat sit amet, consequat dictum velit. Suspendisse pretium dolor eu ex gravida rhoncus convallis in est. In urna metus,</p>', 'css' => 'fab fa-algolia'),
    2 => Array('id' => 3, 'styleid' => 3, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.&nbsp;</p><p><br>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p> <p>&nbsp;</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimum of veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', 'css' => 'fab fa-adn'),
    3 => Array('id' => 4, 'styleid' => 3, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>  <p>&nbsp;</p> <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste</p>', 'css' => 'fas fa-ambulance')
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);