<?php

if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();
$styledata = Array('id' => 18, 'style_name' => 'style18', 'css' => 'heading-font-size |20| heading-font-color |#ffffff| heading-background-color |#0099c7| heading-font-active-color |#ffffff| heading-background-active-color |#3fd9ab| heading-font-familly |Open+Sans| heading-font-weight |600| heading-width |207| heading-padding |15| heading-margin |10| heading-margin-top |20| heading-border-radius |5| heading-box-shadow-Blur |10| heading-box-shadow-color |rgba(222, 222, 222, 1)| content-font-size |16| content-font-color |#7d7d7d| content-background-color |#ffffff| content-padding-top |30| content-padding-right |30| content-padding-bottom |30| content-padding-left |30|content-line-height |1.5| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |center| content-border-radius |5|content-box-shadow-Blur |10| content-box-shadow-color |rgba(196, 196, 196, 1)| heading-font-style |normal| content-box-shadow-Horizontal |0| content-box-shadow-Vertical |0| content-box-shadow-Spread |0| heading-box-shadow-Horizontal |0| heading-box-shadow-Vertical |0| heading-box-shadow-Spread |0| custom-css |0|||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 18, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at magna volutpat, volutpat lectus quis, varius metus. Suspendisse ut velit odio. Sed urna turpis, gravida vel ligula ut, dignissim faucibus elit. Fusce eleifend mollis elit, ullamcorper blandit quam accumsan quis. Donec posuere sem id est ultricies condimentum. Ut accumsan tempor sollicitudin. In ullamcorper leo a lectus ullamcorper, eu condimentum mi posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur eget ligula rutrum, vehicula est malesuada, eleifend odio. In consectetur aliquam elit, eu viverra massa tristique vel. Vivamus in porttitor velit.</p> <p>&nbsp;</p> <p>Proin aliquet pellentesque orci, ut blandit diam dapibus non. Fusce nisl magna, laoreet eu nulla in, scelerisque porta dui. Suspendisse sollicitudin eros ante, nec pretium magna mattis sed. Pellentesque bibendum ut dui id blandit. Vivamus a sapien ex. Etiam posuere scelerisque erat. Sed euismod aliquam leo, non accumsan ex bibendum ut.</p>', 'css' => 'fas fa-address-book'),
    1 => Array('id' => 2, 'styleid' => 18, 'title' => 'Default Title', 'files' => '<p>Proin aliquet pellentesque orci, ut blandit diam dapibus non. Fusce nisl magna, laoreet eu nulla in, scelerisque porta dui. Suspendisse sollicitudin eros ante, nec pretium magna mattis sed. Pellentesque bibendum ut dui id blandit. Vivamus a sapien ex. Etiam posuere scelerisque erat. Sed euismod aliquam leo, non accumsan ex bibendum ut.</p> <p>&nbsp;</p> <p>Duis vel magna est. Donec pharetra, lacus sit amet dapibus dapibus, orci ipsum congue massa, sit amet fermentum tortor odio in libero. Vivamus auctor turpis in malesuada finibus. Maecenas vulputate quis diam vel congue. Duis rhoncus est et diam maximus, non pulvinar nunc porta. Duis orci ligula, posuere at aliquam vitae, semper vel mauris. Etiam vestibulum, nunc nec placerat lobortis, dui tortor interdum dui, ut suscipit mi risus gravida ex. Quisque pharetra libero semper egestas tincidunt. Nulla dapibus, felis vel egestas suscipit, tortor est elementum ante, eget blandit purus nunc id risus. Quisque sed justo eget odio viverra bibendum id vel libero. Etiam malesuada lorem vitae magna bibendum congue eu vitae purus. Aliquam ut mauris sit amet urna faucibus hendrerit. Praesent at ultricies neque. Fusce molestie ornare sapien, eget vehicula purus pretium in.</p>', 'css' => 'fab fa-algolia'),
    2 => Array('id' => 3, 'styleid' => 18, 'title' => 'Default Title', 'files' => '<p>Duis vel magna est. Donec pharetra, lacus sit amet dapibus dapibus, orci ipsum congue massa, sit amet fermentum tortor odio in libero. Vivamus auctor turpis in malesuada finibus. Maecenas vulputate quis diam vel congue. Duis rhoncus est et diam maximus, non pulvinar nunc porta. Duis orci ligula, posuere at aliquam vitae, semper vel mauris. Etiam vestibulum, nunc nec placerat lobortis, dui tortor interdum dui, ut suscipit mi risus gravida ex. Quisque pharetra libero semper egestas tincidunt. Nulla dapibus, felis vel egestas suscipit, tortor est elementum ante, eget blandit purus nunc id risus. Quisque sed justo eget odio viverra bibendum id vel libero. Etiam malesuada lorem vitae magna bibendum congue eu vitae purus. Aliquam ut mauris sit amet urna faucibus hendrerit. Praesent at ultricies neque. Fusce molestie ornare sapien, eget vehicula purus pretium in.</p> <p>&nbsp;</p> <p>Praesent tristique ornare turpis at hendrerit. Nulla rutrum non justo sit amet consequat. Mauris a tempus elit. Sed dignissim vulputate sem. Sed nisi massa, tempus sit amet tortor et, aliquam tincidunt dolor. Aliquam eget justo et dolor placerat condimentum eget non magna. Nam ultricies nec eros vel ultrices. Etiam placerat elementum quam eu volutpat. Cras vestibulum gravida diam id finibus. Donec ac velit est.</p>', 'css' => 'fab fa-adn'),
    3 => Array('id' => 4, 'styleid' => 18, 'title' => 'Default Title', 'files' => '<p>Praesent tristique ornare turpis at hendrerit. Nulla rutrum non justo sit amet consequat. Mauris a tempus elit. Sed dignissim vulputate sem. Sed nisi massa, tempus sit amet tortor et, aliquam tincidunt dolor. Aliquam eget justo et dolor placerat condimentum eget non magna. Nam ultricies nec eros vel ultrices. Etiam placerat elementum quam eu volutpat. Cras vestibulum gravida diam id finibus. Donec ac velit est.</p> <p>&nbsp;</p> <p>Praesent eget semper tellus, ac dapibus augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas vitae justo nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut maximus efficitur leo scelerisque condimentum. Vivamus convallis nisi in nibh interdum mattis. Quisque non arcu aliquet, lacinia turpis eget, tincidunt justo. In molestie faucibus rutrum. Maecenas sit amet fringilla urna, eu interdum felis. Proin dapibus est vel commodo dapibus. Nulla accumsan ante orci, eu iaculis mi pulvinar sit amet. Donec eleifend augue sit amet mauris varius aliquam. Pellentesque ac lectus elit. Ut interdum tempus nunc, vitae ultrices urna elementum sed.</p>', 'css' => 'fas fa-ambulance')
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);
