<?php
if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();
$styledata = Array('id' => 21, 'style_name' => 'style21', 'css' => 'heading-font-size |20| heading-font-color |#8c8c8c| heading-font-active-color |#bd068f| heading-border-size |2| heading-border-color |#bd9fb5| heading-border-active-color |#bd068f| heading-font-familly |Open+Sans| heading-font-weight |500| heading-text-align |center|heading-width |200| heading-padding |20| content-font-size |16| content-font-color |#949494| content-background-color |rgba(255, 255, 255, 1)| content-padding-top |30| content-padding-right |30| content-padding-bottom |30| content-padding-left |30|content-line-height |1.5| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |center| content-border-radius |5|content-box-shadow-Blur |10| content-box-shadow-color |rgba(224, 224, 224, 1)| content-box-shadow-Horizontal |0| content-box-shadow-Vertical |0| content-box-shadow-Spread |0| heading-font-style |normal| custom-css ||||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 21, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget dui ac elit tempus accumsan in id tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec eget luctus nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id feugiat justo, in ultrices neque. Aenean dignissim augue at quam molestie lobortis. Curabitur rhoncus erat neque, sed sagittis velit ultricies non. Maecenas bibendum efficitur porta.</p> <p>&nbsp;</p> <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi bibendum turpis sit amet velit pretium tincidunt. Curabitur tellus purus, sagittis vitae facilisis ac, aliquet quis lacus. Cras aliquam et tortor nec tempus. Sed posuere tortor id volutpat mollis. Integer efficitur nec eros ac pulvinar. Nulla sed ultricies nisi.</p>', 'css' => 'fas fa-address-book'),
    1 => Array('id' => 2, 'styleid' => 21, 'title' => 'Default Title', 'files' => '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi bibendum turpis sit amet velit pretium tincidunt. Curabitur tellus purus, sagittis vitae facilisis ac, aliquet quis lacus. Cras aliquam et tortor nec tempus. Sed posuere tortor id volutpat mollis. Integer efficitur nec eros ac pulvinar. Nulla sed ultricies nisi.</p> <p>&nbsp;</p> <p>Aenean luctus nulla et tincidunt sodales. Pellentesque massa lacus, elementum eget congue id, convallis eu magna. Pellentesque vehicula, tortor luctus venenatis varius, magna lectus commodo purus, et ornare urna nisi vitae eros. Vivamus vulputate accumsan tincidunt. Sed eleifend id risus eget suscipit. Suspendisse tristique tristique ligula, vitae lobortis metus pulvinar vel. Maecenas quis nisl in nisi vestibulum tristique. Donec consectetur suscipit augue. Curabitur a nibh sed mi tempor interdum ac blandit velit. Quisque egestas, mauris ac vestibulum posuere, ex felis posuere turpis, non fringilla neque risus in odio. Nulla gravida sem metus, in viverra erat gravida nec. Proin vehicula imperdiet nisl quis elementum. Nulla ac pharetra diam, sed congue quam. Quisque blandit, neque sed dapibus consectetur, sem quam aliquet est, in congue dolor dui eget massa. Nam maximus massa eu nulla suscipit interdum. Nam mollis hendrerit turpis a congue.</p>', 'css' => 'fab fa-algolia'),
    2 => Array('id' => 3, 'styleid' => 21, 'title' => 'Default Title', 'files' => '<p>Suspendisse enim ipsum, dapibus tristique odio in, auctor porta arcu. Proin ut suscipit dolor. Nullam tristique bibendum venenatis. Curabitur nibh diam, lobortis ut nunc vel, vehicula maximus ipsum. Proin interdum ex diam, et aliquam sem suscipit nec. Maecenas tellus ante, egestas in fermentum nec, facilisis eget dolor. Maecenas viverra consequat ante in accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam faucibus leo eu nisl euismod, ut varius arcu gravida.</p> <p>&nbsp;</p><p>Pellentesque non ornare ante. Suspendisse potenti. Cras et sem risus. Sed eleifend neque sed orci finibus finibus. Etiam euismod velit nec efficitur fringilla. Vestibulum enim enim, finibus a diam eu, tempor sodales erat. Aenean aliquet nulla imperdiet ex porttitor fringilla. Quisque id nisl in massa lobortis iaculis ac nec justo. Sed molestie vel diam ut ultricies. Aliquam ut ante malesuada, pretium lacus id, pellentesque lectus. Etiam eu hendrerit nulla, eu fermentum mauris. Quisque a aliquet magna.</p>', 'css' => 'fab fa-adn'),
    3 => Array('id' => 4, 'styleid' => 21, 'title' => 'Default Title', 'files' => '<p>Aenean luctus nulla et tincidunt sodales. Pellentesque massa lacus, elementum eget congue id, convallis eu magna. Pellentesque vehicula, tortor luctus venenatis varius, magna lectus commodo purus, et ornare urna nisi vitae eros. Vivamus vulputate accumsan tincidunt. Sed eleifend id risus eget suscipit. Suspendisse tristique tristique ligula, vitae lobortis metus pulvinar vel. Maecenas quis nisl in nisi vestibulum tristique. Donec consectetur suscipit augue. Curabitur a nibh sed mi tempor interdum ac blandit velit. Quisque egestas, mauris ac vestibulum posuere, ex felis posuere turpis, non fringilla neque risus in odio. Nulla gravida sem metus, in viverra erat gravida nec. Proin vehicula imperdiet nisl quis elementum. Nulla ac pharetra diam, sed congue quam. Quisque blandit, neque sed dapibus consectetur, sem quam aliquet est, in congue dolor dui eget massa. Nam maximus massa eu nulla suscipit interdum. Nam mollis hendrerit turpis a congue.</p>  <p>&nbsp;</p><p>Suspendisse enim ipsum, dapibus tristique odio in, auctor porta arcu. Proin ut suscipit dolor. Nullam tristique bibendum venenatis. Curabitur nibh diam, lobortis ut nunc vel, vehicula maximus ipsum. Proin interdum ex diam, et aliquam sem suscipit nec. Maecenas tellus ante, egestas in fermentum nec, facilisis eget dolor. Maecenas viverra consequat ante in accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam faucibus leo eu nisl euismod, ut varius arcu gravida.</p>', 'css' => 'fas fa-ambulance')
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);
