<?php 
if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();

$styledata = Array('id' => 22, 'style_name' => 'style22', 'css' => 'heading-font-size |20| heading-font-color |#ffffff| heading-background-color |#616161| heading-font-active-color |#ffffff| heading-font-background-color |#10aad1| heading-font-familly |Open+Sans| heading-font-weight |500| heading-position |left| heading-padding |20| heading-margin-bottom |2| content-font-size |16| content-font-color |#8a8a8a| content-background-color |rgba(255, 255, 255, 1)| content-width |75.5| content-padding-top |30| content-padding-right |30| content-padding-bottom |30| content-padding-left |30|content-line-height |1.5| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |left| content-border-radius |5|content-box-shadow-Blur |10| content-box-shadow-color |rgba(214, 214, 214, 1)| heading-font-style |normal| content-box-shadow-Horizontal |0| content-box-shadow-Vertical |0| content-box-shadow-Spread |0| custom-css ||||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 22, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non massa dapibus, euismod urna eget, rutrum nulla. Aenean rutrum risus augue, laoreet tristique libero tincidunt at.&nbsp;</p> <p>&nbsp;</p> <p>In cursus, leo vitae dapibus egestas, felis neque consequat libero, porta sodales orci leo vel sapien. Donec vitae justo scelerisque, tincidunt metus sed, convallis ligula. Duis massa sapien, molestie non magna in, pharetra aliquam nunc. Nam id est ac sapien faucibus ullamcorper vitae sed turpis.</p>', 'css' => 'fas fa-address-book'),
    1 => Array('id' => 2, 'styleid' => 22, 'title' => 'Default Title', 'files' => '<p>Phasellus efficitur massa sed efficitur venenatis. Aliquam quis lectus lobortis, maximus libero et, sollicitudin lacus. Sed ac tincidunt tellus. Praesent id tristique nisl, sed sollicitudin est. In sit amet finibus magna. Pellentesque efficitur libero at ipsum molestie, ut sollicitudin neque fringilla.</p> <p>&nbsp;</p> <p>Donec non risus blandit, cursus velit eget, commodo quam. Praesent a facilisis leo, nec sodales odio. Donec malesuada nisi in aliquam scelerisque. Cras odio velit, fringilla id nisl at, iaculis posuere loree.</p>', 'css' => 'fab fa-algolia'),
    2 => Array('id' => 3, 'styleid' => 22, 'title' => 'Default Title', 'files' => '<p>Maecenas accumsan risus metus, ut feugiat dolor pretium vel. Vestibulum lobortis ultrices ante, id efficitur lectus blandit in.</p> <p>&nbsp;</p> <p>Morbi quis nisl nulla. In finibus lectus fermentum ipsum facilisis, a placerat augue lobortis. Nullam sodales lacus nec vulputate faucibus. Nullam sodales nulla vitae magna consectetur condimentum. Curabitur efficitur ut ipsum vitae lobortis. Ut id feugiat purus, eu viverra libero. Aenean at consectetur leo. Morbi tristique lorem vitae eleifend interdum. Duis at est sem. Phasellus a condimentum arcu, a egestas massa.</p>', 'css' => 'fab fa-adn'),
    3 => Array('id' => 4, 'styleid' => 22, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non massa dapibus, euismod urna eget, rutrum nulla. Aenean rutrum risus augue, laoreet tristique libero tincidunt at. Nullam venenatis lobortis turpis, et condimentum mauris rutrum mattis. Pellentesque porta ornare lorem ut luctus.</p> <p>&nbsp;</p> <p>In cursus, leo vitae dapibus egestas, felis neque consequat libero, porta sodales orci leo vel sapien. Donec vitae justo scelerisque, tincidunt metus sed, convallis ligula. Duis massa sapien, molestie non magna in, pharetra aliquam nunc. Nam id est ac sapien faucibus ullamcorper vitae sed turpis.</p>', 'css' => 'fas fa-ambulance')
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);