<?php
if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();

$styledata = Array('id' => 2, 'style_name' => 'style2', 'css' => 'heading-font-size |20| heading-font-color |#828282| heading-background-color |rgba(55, 61, 67, 1)| heading-font-active-color |#ffffff| heading-font-familly |Open+Sans| heading-font-weight |500| heading-text-align |center| heading-width |220| heading-padding |15| heading-Border-radius |7| content-font-size |16| content-font-color |#6e6e6e| content-background-color |#ffffff| content-padding-top |20| content-padding-right |20| content-padding-bottom |20| content-padding-left |20| content-line-height |1.2| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |left| content-box-shadow-Blur |20| content-box-shadow-color |rgba(204, 204, 204, 1)| heading-font-style |normal| content-box-shadow-Horizontal |0| content-box-shadow-Vertical |0| content-box-shadow-Spread |0| custom-css |||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 2, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p> <p>&nbsp;</p> <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste</p>', 'css' => 'fas fa-address-book'),
    1 => Array('id' => 2, 'styleid' => 2, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident</p> <p>&nbsp;</p> <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste</p>', 'css' => 'fab fa-algolia'),
    2 => Array('id' => 3, 'styleid' => 2, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <p>&nbsp;</p> <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident</p>', 'css' => 'fab fa-adn'),
    3 => Array('id' => 4, 'styleid' => 2, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <p>&nbsp;</p> <p> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident</p>', 'css' => 'fas fa-ambulance')
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);
