<?php
if (!defined('ABSPATH'))
    exit;
responsive_tabs_with_accordions_user_capabilities();
$styledata = Array('id' => 15, 'style_name' => 'style15', 'css' => 'heading-font-size |20| heading-font-color |#ffffff| heading-background-color |rgba(135, 34, 153, 1)| heading-font-active-color |#ffffff| heading-background-active-color |rgba(185, 4, 217, 1)| heading-font-familly |Open+Sans| heading-font-weight |500| heading-padding |20| heading-icon-size |20| heading-margin-bottom |3| content-font-size |16| content-font-color |#a3a3a3| content-background-color |rgba(255, 255, 255, 1)| content-padding-top |30| content-padding-right |30| content-padding-bottom |30| content-padding-left |30| content-width |75| content-line-height |1.5| content-font-familly |Open+Sans| content-font-weight |300| content-font-align |left| content-border-radius |5|content-box-shadow-Blur |10| content-box-shadow-color |rgba(219, 219, 219, 1)| heading-position |left| heading-font-style |normal| content-box-shadow-Horizontal |0| content-box-shadow-Vertical |0| content-box-shadow-Spread |0| custom-css ||||||||||');
$listdata = Array(
    0 => Array('id' => 1, 'styleid' => 15, 'title' => 'Default Title', 'files' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie, purus vitae pulvinar sodales, diam sapien hendrerit tortor, id rhoncus ipsum urna non tellus. Vivamus eros.</p> <p>&nbsp;</p> <p>In hac habitasse platea dictumst. Sed auctor, neque non laoreet ultricies, nisl ligula consectetur nisl, nec finibus neque enim nec elit. Sed dapibus sed turpis sit amet facilisis. Nam varius mi ipsum, vitae ultrices nunc scelerisque sed.</p>', 'css' => VcTabsAdminFontAwesomeData('book')),
    1 => Array('id' => 2, 'styleid' => 15, 'title' => 'Default Title', 'files' => '<p>Sed nec leo turpis. Donec justo dui, maximus nec lacinia eget, tincidunt efficitur eros. Pellentesque congue sem sem, et tempus lectus finibus eget. Aliquam semper sit amet eros vel pulvinar.</p> <p>&nbsp;</p> <p>Sed suscipit est ut risus scelerisque egestas. Nullam eu scelerisque dui. Nam tempor aliquam justo et efficitur. Cras mauris velit, volutpat a ornare a, tincidunt eu ipsum. Maecenas vulputate tincidunt cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.&nbsp;</p>', 'css' => VcTabsAdminFontAwesomeData('github')),
    2 => Array('id' => 3, 'styleid' => 15, 'title' => 'Default Title', 'files' => '<p>Integer congue ipsum ut dui sodales mattis at eget velit. Nulla sapien magna, mollis a facilisis a, auctor sit amet ex. Donec efficitur neque eros, nec condimentum dolor dapibus suscipit. Duis gravida turpis vel massa facilisis, at porttitor metus tempus. Sed et sem a lectus efficitur vulputate. Vivamus ullamcorper nisl nec massa facilisis molestie.</p> <p>&nbsp;</p> <p>In hac habitasse platea dictumst. Aliquam luctus, odio et sagittis vulputate, ex ex efficitur ligula, ac bibendum tortor metus vel lorem.. Quisque consectetur et massa in mollis.</p>', 'css' => VcTabsAdminFontAwesomeData('adn')),
    3 => Array('id' => 4, 'styleid' => 15, 'title' => 'Default Title', 'files' => '<p>Sed quis quam eget sem ultrices mattis ut at nisl. Cras commodo fringilla dui, vel viverra magna rhoncus vitae. Aenean vehicula gravida nulla a volutpat. Nulla facilisi.</p> <p>&nbsp;</p> <p>Praesent dictum ultrices mi, lacinia facilisis quam elementum at. Vestibulum fermentum sollicitudin risus, ac ornare orci dictum in. Donec scelerisque, dui eget gravida blandit, leo nibh lacinia purus, in venenatis libero nisi et ante. Proin pellentesque nunc eu tempor posuere.&nbsp;</p>', 'css' => VcTabsAdminFontAwesomeData('ambulance'))
);
echo '<input type="hidden" name="oxi-tabs-data-' . $styledata['id'] . '" id="oxi-tabs-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
echo ctu_admin_style_layouts($styledata, $listdata);